-- ****** Object: Constraint HR.DEPT_MGR_FK Script Date: 3/2/2016 6:39:58 PM ******
ALTER TABLE "DEPARTMENTS" ADD CONSTRAINT "DEPT_MGR_FK" FOREIGN KEY ("MANAGER_ID") REFERENCES "EMPLOYEES"("EMPLOYEE_ID") ENABLE;
