-- ****** Object: Constraint HR.DEPT_LOC_FK Script Date: 3/2/2016 6:39:58 PM ******
ALTER TABLE "DEPARTMENTS" ADD CONSTRAINT "DEPT_LOC_FK" FOREIGN KEY ("LOCATION_ID") REFERENCES "LOCATIONS"("LOCATION_ID") ENABLE;
