-- ****** Object: Constraint HR.EMP_MANAGER_FK Script Date: 3/2/2016 6:39:58 PM ******
ALTER TABLE "EMPLOYEES" ADD CONSTRAINT "EMP_MANAGER_FK" FOREIGN KEY ("MANAGER_ID") REFERENCES "EMPLOYEES"("EMPLOYEE_ID") ENABLE;
