-- ****** Object: Constraint HR.JHIST_DEPT_FK Script Date: 3/2/2016 6:39:58 PM ******
ALTER TABLE "JOB_HISTORY" ADD CONSTRAINT "JHIST_DEPT_FK" FOREIGN KEY ("DEPARTMENT_ID") REFERENCES "DEPARTMENTS"("DEPARTMENT_ID") ENABLE;
