-- ****** Object: Constraint HR.JHIST_EMP_FK Script Date: 3/2/2016 6:39:58 PM ******
ALTER TABLE "JOB_HISTORY" ADD CONSTRAINT "JHIST_EMP_FK" FOREIGN KEY ("EMPLOYEE_ID") REFERENCES "EMPLOYEES"("EMPLOYEE_ID") ENABLE;
