-- ****** Object: Constraint HR.LOC_C_ID_FK Script Date: 3/2/2016 6:39:58 PM ******
ALTER TABLE "LOCATIONS" ADD CONSTRAINT "LOC_C_ID_FK" FOREIGN KEY ("COUNTRY_ID") REFERENCES "COUNTRIES"("COUNTRY_ID") ENABLE;
