-- ****** Object: Table HR.REGIONS Script Date: 3/2/2016 6:39:58 PM ******
  CREATE TABLE "REGIONS" 
   (	"REGION_ID" NUMBER CONSTRAINT "REGION_ID_NN" NOT NULL ENABLE,
	"REGION_NAME" VARCHAR2(25),
	CONSTRAINT "REG_ID_PK" PRIMARY KEY ("REGION_ID") ENABLE
   );